//AUTOGENERATED FILE FROM png2asset
// Conversion args: Ball.png -keep_palette_order

#ifndef METASPRITE_Ball_H
#define METASPRITE_Ball_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Ball_TILE_ORIGIN 0
#define Ball_TILE_W 8
#define Ball_TILE_H 16
#define Ball_WIDTH 16
#define Ball_HEIGHT 16
#define Ball_TILE_COUNT 2
#define Ball_PALETTE_COUNT 1
#define Ball_COLORS_PER_PALETTE 4
#define Ball_TOTAL_COLORS 4
#define Ball_PIVOT_X 8
#define Ball_PIVOT_Y 8
#define Ball_PIVOT_W 16
#define Ball_PIVOT_H 16
extern const metasprite_t* const Ball_metasprites[1];

BANKREF_EXTERN(Ball)

extern const palette_color_t Ball_palettes[4];
extern const uint8_t Ball_tiles[32];

#endif
