//AUTOGENERATED FILE FROM png2asset
// Conversion args: Tileset.png -spr8x8 -noflip -keep_palette_order

#ifndef METASPRITE_Tileset_H
#define METASPRITE_Tileset_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Tileset_TILE_ORIGIN 0
#define Tileset_TILE_W 8
#define Tileset_TILE_H 8
#define Tileset_WIDTH 80
#define Tileset_HEIGHT 8
#define Tileset_TILE_COUNT 9
#define Tileset_PALETTE_COUNT 1
#define Tileset_COLORS_PER_PALETTE 4
#define Tileset_TOTAL_COLORS 4
#define Tileset_PIVOT_X 40
#define Tileset_PIVOT_Y 4
#define Tileset_PIVOT_W 80
#define Tileset_PIVOT_H 8
extern const metasprite_t* const Tileset_metasprites[1];

BANKREF_EXTERN(Tileset)

extern const palette_color_t Tileset_palettes[4];
extern const uint8_t Tileset_tiles[144];

#endif
