//AUTOGENERATED FILE FROM png2asset
// Conversion args: Tilemap.png -spr8x8 -noflip -map -keep_palette_order -source_tileset Tileset.png

#ifndef METASPRITE_Tilemap_H
#define METASPRITE_Tilemap_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Tilemap_TILE_ORIGIN 0
#define Tilemap_TILE_W 8
#define Tilemap_TILE_H 8
#define Tilemap_WIDTH 160
#define Tilemap_HEIGHT 144
#define Tilemap_TILE_COUNT 0
#define Tilemap_PALETTE_COUNT 1
#define Tilemap_COLORS_PER_PALETTE 4
#define Tilemap_TOTAL_COLORS 4
#define Tilemap_MAP_ATTRIBUTES 0
extern const unsigned char Tilemap_map[360];
#define Tilemap_map_attributes Tilemap_map

BANKREF_EXTERN(Tilemap)


#endif
