//AUTOGENERATED FILE FROM png2asset
// Conversion args: Ball.png -keep_palette_order

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(Ball)

const palette_color_t Ball_palettes[4] = {
	RGB8(255,255,255), RGB8(212,212,212), RGB8(138,138,138), RGB8(  0,  0,  0)
	};

const uint8_t Ball_tiles[32] = {
	0x07,0x00,0x0f,0x00,0x1c,0x03,0x30,0x0f,0x63,0x1f,0xe7,0x1f,0xcf,0x3f,0xcf,0x3f,
	0xcf,0x3f,0xcf,0x3f,0xe7,0x1f,0x63,0x1f,0x30,0x0f,0x1c,0x03,0x0f,0x00,0x07,0x00
	};

const metasprite_t Ball_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 0, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const Ball_metasprites[1] = {
	Ball_metasprite0
};
